---
- name: override ssh ansible_ssh_executable
  run_once: True
  when:
  - inventory_hostname == ansible_play_hosts[0]
  - ansible_play_hosts_all
    | map('extract', hostvars)
    | rejectattr('ansible_become_method', 'defined')
    | list
    | length > 0
  connection: ssh
  vars:
  - ansible_connection: ssh
  - ansible_ssh_executable: "{{ role_path }}/files/dump-ssh-opts.sh"
  assert:
    that:
    - "[ansible_connection] | intersect(['ssh', 'smart']) | list | length == 1"
    - "ansible_ssh_executable == (role_path + '/files/dump-ssh-opts.sh')"

- name: save inventory ssh pipelining status
  when: ansible_inventory_ssh_pipelining_is_not_defined is not defined
  set_fact:
    ansible_inventory_ssh_pipelining_is_not_defined: "{{ hostvars[inventory_hostname].ansible_ssh_pipelining is not defined }}"

- block:
  - name: current local user
    when: ansible_local_user is not defined
    run_once: True
    set_fact:
      ansible_local_user: "{{ require_local_command['PATH='+lookup('env','PATH')|quote]['id']
                                  | ternary(lookup('pipe', 'id -un'), '')
                                  | d(require_local_command['PATH='+lookup('env','PATH')|quote]['whoami']
                                      | ternary(lookup('pipe', 'whoami'), '')
                                      , True)
                                  | d(lookup('env', 'USER'), True) }}"
    failed_when: ansible_local_user == ''

  - name: parse become method
    when: ansible_become_method is not defined
    register: detect_become_method
    become: True
    become_user: :fakeuser{{ lookup('pipe', 'echo $PPID') }}
    connection: ssh
    vars:
    - ansible_connection: ssh
    - ansible_ssh_executable: "{{ role_path | quote }}/files/parse-become-method.sh"
    - ansible_become: True
    - ansible_become_user: :fakeuser{{ lookup('pipe', 'echo $PPID') }}
    raw: --FAKE::::COMMAND={{ lookup('pipe', 'echo $PPID') }}
    failed_when: detect_become_method.stderr | d() != ''
    changed_when: False

  ## check sudo flags for old version
  ## when the become method is sudo, we will check for every remote machine:
  ##   0. have a sudo with -n option: keep default sudo flags;
  ##   1. have a sudo without -n option: remove -n from default sudo flags;
  ##   2. no sudo command, do nothing.
  - block:

    - name: detecting sudo version
      register: detect_sudo_version
      become: False
      become_user: "{{ ansible_user | d(ansible_local_user, True) }}"
      vars:
      - ansible_become: False
      - ansible_become_user: "{{ ansible_user | d(ansible_local_user, True) }}"
      raw: "{{ ansible_become_exe | d('sudo', True) | quote }} -V"
      failed_when: ( [ detect_sudo_version.rc ] | intersect([0, 1, 127]) | list | length == 0 )
      changed_when: False

    - name: update sudo flag
      vars:
      - sudo_version: "{{ detect_sudo_version.stdout_lines
                          | select('match', 'Sudo version .*')
                          | first
                          | d('')
                          | regex_replace('^[^0-9]*', '')
                          | d('0.0', True) }}"
      when:
      - detect_sudo_version.rc == 0 or detect_sudo_version.rc == 1
      - (  detect_sudo_version.stdout_lines
           | select('match', 'Sudo version .*')
           | list
           | length >= 1
        or detect_sudo_version.stderr
           | d('')
           | search('sudo. (invalid|illegal) option')
        )
      - ( ansible_become_flags | d('-H -S -n', True) )
        == ( sudo_version | version_compare('1.7', '>=') | ternary('-H -S', '-H -S -n') )
      set_fact:
        ansible_become_flags: "{{ sudo_version | version_compare('1.7', '>=') | ternary('', '-H -S') }}"

    when:
    - ansible_version.full | version_compare('2.2', '>=')
    - ansible_become_method | d(detect_become_method.stdout) | d('sudo', True) == 'sudo'
    - ( [ ansible_become_flags | d('-H -S -n', True) ] | intersect(['-H -S', '-H -S -n']) | list | length == 1 )

  ## NOTE: When become method is 'su', it will ignore ansible_ssh_pipelining,
  ##       so only detect for 'sudo' and unknown methods,
  ##       and enable ssh pipelining for all other known methods.
  ##
  ## NOTE: Having remote hosts without 'sudo' command,
  ##       or become flags containing invalid options, we also enable pipelining,
  ##       cause a become-task will always fail in this scenario.
  ##
  ## TODO: support custom ansible_become_exe
  - name: detecting
    when: ([ ansible_become_method | d(detect_become_method.stdout) | d('sudo', True) ])
          | intersect(['sudo', 'UNKNOWN-BECOME-METHOD'])
          | list
          | length > 0
    register: detect_pipelining
    become: True
    become_user: "{{ (   (ansible_become_user | d('root', True) != 'root')
                     and (ansible_become_user | d('root', True)) == (ansible_user | d(ansible_local_user, True))
                     )
                     | ternary('root', ansible_become_user | d('root', True)) }}"
    vars:
    - ansible_ssh_pipelining: True
    - ansible_become: True
    - ansible_become_user: "{{ (   (ansible_become_user | d('root', True) != 'root')
                               and (ansible_become_user | d('root', True)) == (ansible_user | d(ansible_local_user, True))
                               )
                               | ternary('root', ansible_become_user | d('root', True)) }}"
    ping:
    failed_when: False
    changed_when: False
    ignore_errors: True

  - name: flipping
    vars:
    - detect_string: "{{ (detect_pipelining.module_stdout | d()) + '\n' + (detect_pipelining.module_stderr | d()) }}"
    when: ansible_ssh_pipelining != (
            [ ansible_become_method | d(detect_become_method.stdout) | d('sudo', True) ]
            | intersect(['sudo', 'UNKNOWN-BECOME-METHOD'])
            | list
            | length == 0
            or
            ( detect_string.find('must have a tty') == -1 and
              detect_string.find('no tty present') == -1
            )
          )
    set_fact:
      ansible_ssh_pipelining: "{{ not ansible_ssh_pipelining }}"

  when:
  - ansible_inventory_ssh_pipelining_is_not_defined
  - lookup('env', 'ANSIBLE_SSH_PIPELINING') == ''
  - local_ansible_config['ssh_connection/pipelining'] is not defined
