---
- name: save inventory ssh pipelining status
  when: ansible_inventory_ssh_pipelining_defined is not defined
  set_fact:
    ansible_inventory_ssh_pipelining_defined: "{{ hostvars[inventory_hostname].ansible_ssh_pipelining is defined }}"

- block:
  - name: detecting
    register: detect_pipelining
    become: True
    vars:
      ansible_ssh_pipelining: True
      ansible_become_pass: '.'
      ansible_python_interpreter: exit
    ping:
    failed_when: False
    #- detect_pipelining.module_stderr is not defined or detect_pipelining.module_stdout is not defined
    #- detect_pipelining.msg != 
    changed_when: False
    ignore_errors: True

  - name: flipping
    when: ansible_ssh_pipelining != (
            (detect_pipelining.module_stderr | d()).find('must have a tty') == -1 and
            (detect_pipelining.module_stdout | d()).find('must have a tty') == -1 and
            (detect_pipelining.module_stderr | d()).find('no tty present') == -1 and
            (detect_pipelining.module_stdout | d()).find('no tty present') == -1 and
            (detect_pipelining.module_stderr | d()).find('must be run from a terminal') == -1 and
            (detect_pipelining.module_stdout | d()).find('must be run from a terminal') == -1 and
            (detect_pipelining.module_stderr | d()).find('standard in must be a tty') == -1 and
            (detect_pipelining.module_stdout | d()).find('standard in must be a tty') == -1 and
            (detect_pipelining.module_stderr | d()).find('su{{':'}} must be suid to work properly') == -1 and
            (detect_pipelining.module_stdout | d()).find('su{{':'}} must be suid to work properly') == -1 and
            (detect_pipelining.module_stderr | d()).find('su{{':'}} incorrect password') == -1 and
            (detect_pipelining.module_stdout | d()).find('su{{':'}} incorrect password') == -1 and
            True
          )
    set_fact:
      ansible_ssh_pipelining: "{{ not ansible_ssh_pipelining }}"

  when:
  - not ansible_inventory_ssh_pipelining_defined
  - lookup('env', 'ANSIBLE_SSH_PIPELINING') == ''
  - local_ansible_config['ssh_connection/pipelining'] is not defined
