---
- name: override ssh ansible_ssh_executable
  run_once: True
  when: inventory_hostname == ansible_play_hosts[0]
  connection: ssh
  vars:
  - ansible_connection: ssh
  - ansible_ssh_executable: "{{ role_path }}/files/dump-ssh-opts.sh"
  assert:
    that:
    - "[ansible_connection] | intersect(['ssh', 'smart']) | list | length == 1"
    - "ansible_ssh_executable == (role_path + '/files/dump-ssh-opts.sh')"

- name: save inventory ssh pipelining status
  when: ansible_inventory_ssh_pipelining_is_not_defined is not defined
  set_fact:
    ansible_inventory_ssh_pipelining_is_not_defined: "{{ hostvars[inventory_hostname].ansible_ssh_pipelining is not defined }}"

- block:
  - name: parse become method
    register: detect_become_method
    become: True
    connection: ssh
    vars:
    - ansible_connection: ssh
    - ansible_ssh_executable: "{{ role_path | quote }}/files/parse-become-method.sh"
    - ansible_become: True
    raw: --FAKE::::COMMAND={{ lookup('pipe', 'echo $PPID') }}
    changed_when: False

  ## NOTE: When become method is 'su', it will ignore ansible_ssh_pipelining,
  ##       so only detect for 'sudo', and enable ssh pipelining for all others.
  ##
  ## NOTE: For old version sudo (not support -n option), it will always enable ssh pipelining
  ##
  ## NOTE: Having remote host without 'sudo' command, we also enable pipelining,
  ##       cause a become-task will always fail in this scenario.
  ##
  ## TODO: support custom ansible_become_exe
  - name: detecting
    when: detect_become_method.stdout | d('sudo', True) == 'sudo'
    register: detect_pipelining
    become: True
    vars:
      ansible_ssh_pipelining: True
      ansible_become: True
    ping:
    failed_when: False
    changed_when: False
    ignore_errors: True

  - name: flipping
    vars:
    - detect_string: "{{ (detect_pipelining.module_stdout | d()) + '\n' + (detect_pipelining.module_stderr | d()) }}"
    when: ansible_ssh_pipelining != (
            detect_become_method.stdout | d('sudo', True) != 'sudo' or
            ( detect_string.find('must have a tty') == -1 and
              detect_string.find('no tty present') == -1
            )
          )
    set_fact:
      ansible_ssh_pipelining: "{{ not ansible_ssh_pipelining }}"

  when:
  - ansible_inventory_ssh_pipelining_is_not_defined
  - lookup('env', 'ANSIBLE_SSH_PIPELINING') == ''
  - local_ansible_config['ssh_connection/pipelining'] is not defined
