galaxy_info:
  role_name: smart_ssh_pipelining
  namespace: gzm55
  author: James Z.M. Gao
  description: Try to detect ssh pipeling if needed.

  license: BSD

  # ConfigManager api requires 2.5
  # ansible.builtin.* requires 2.8
  min_ansible_version: 2.8

  platforms:
  - name: GenericBSD
    versions: [all]
  - name: GenericLinux
    versions: [all]
  - name: Windows
    versions: [all]
  - name: GenericUNIX
    versions: [all]

  galaxy_tags: [system, network]

allow_duplicates: yes
dependencies: []
